### ISSUE TITLE
Should we remove the packages page in favor of linking to the npm page?

### ISSUE THREAD

**Issue by Validark** [roblox-ts/roblox-ts.github.io#33]
All packages are listed under: https://www.npmjs.com/org/rbxts

@evaera Do you want to keep the packages page (and add that search function) or just link to the npmjs page?

**Comment by evaera** [comment]
I would rather change it to be a "featured packages" page rather than removing it entirely.

**Comment by Validark** [comment]
What would be the difference? Would it be curated? You said before we got the rbxts namespace that you wanted all packages on there. Now, will it just be your favorites?

**Comment by osyrisrblx** [comment]
Some packages are absolutely more "official" or useful than other packages. i.e. `@rbxts/roact`, `@rbxts/rodux`, etc.

Featured packages allow us to show the best of our ecosystem to people who don't know anything about roblox-ts yet. If we have 100+ packages on the npm page, users don't immediately know which packages are most popular / useful / etc.

There's definitely value in more niche packages but I don't think they're worth featuring.
